require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadYamlPath = "Homestead.yaml"
homesteadJsonPath = "Homestead.json"
afterScriptPath = "after.sh"
aliasesPath = "aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exists? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
        Homestead.configure(config, settings)
    elsif File.exists? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
        Homestead.configure(config, settings)
    end

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath
    end

    # Site settings
    settings["sites"].each do |site|
        rootPath = site["to"].sub(/public$/, '');

        # Migrate database
        if (site.has_key?("migrate") && site["migrate"])
            config.vm.provision "shell",
                inline: "php " + rootPath + "artisan migrate"
        end

        # Run queue worker
        if (site.has_key?("queue") && site["queue"])
            config.vm.provision "shell", path: "scripts/queue-worker.sh", args: [rootPath, site["map"]]
        end
    end
end
